### ISSUE TITLE
DirectoryNotFoundException - when C:\temp is missing

### ISSUE THREAD

**Issue by szyb** [Grauenwolf/Tortuga-TestMonkey#16]
TestGenerator seems to require of existence c:\temp. Is this a part of TestMonkey or Source Generator?

`warning CS8785: Generator 'TestGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'DirectoryNotFoundException' with message 'Could not find a part of the path 'C:\temp\build_log.txt'.'`

version: 0.2.0
dotnet: 6
test framework: XUnit

**Comment by Grauenwolf** [comment]
You're using an old version. The commit on May 16, 2021 removes that temp file.

But you may want to get the check-in I just made. Last night I fixed a bug in the semantic parser.

**Comment by Grauenwolf** [comment]
Oh wait, you're pulling from Nuget.org. Let me fix that for you...

**Comment by Grauenwolf** [comment]
Ok, this time it's fixed for real. If you're use the package (as opposed to the source code), use version 0.3.

https://www.nuget.org/packages/Tortuga.TestMonkey/0.3.0

Thank you for bringing this to my attention.

**Comment by szyb** [comment]
Thanks, now it works without c:\temp :)

**Comment by Grauenwolf** [comment]
If you have any design suggestions or requests feel free to send them my way.

Originally this was created to just demonstrate writing Source Generators, but now I'm ready to start building it out as a real tool. (I literally picked  it up again the day before you found the bug.)

**Comment by szyb** [comment]
That is how I find it, by reading your article. I love the source generator idea and use this generator in one of my projects. I find it very useful and looking forward to see more robust tool. Great work!
